name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: "3,8,13,18,23,28,33,38,43,48,53,58 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          date -u
